### ISSUE TITLE
Icon Missing

### ISSUE THREAD

**Issue by Thr33D** [cowboysdude/MMM-NOAA3#10]
Just updated to the newest version.  The icon is not showing.

Here is my config.js
`{
                        module: "MMM-NOAA3",
                        position: "top_right",
                        config: {
                                provider: "openweather",
                                apiKey: "XXX",
                                airKey: "XXXX",
                                css: "NOAA4",
                                userlat: "27.9330847",
                                userlon: "-82.4939544"
}
},
`
Here is what it looks like:
![screen shot 2018-09-22 at 9 32 09 pm](https://user-images.githubusercontent.com/43507964/45923442-0c075d00-beb4-11e8-9366-97e143b23cd6.png)

**Comment by Thr33D** [comment]
Update.  Letting it run for a while (like all night) the icon is now working.  Looks good, I will keep an eye on it and provide any changes.  But as of now, it looks good.

**Comment by cowboysdude** [comment]
On vacation will look at it this week when i get back. 😉

**Comment by Rutul27** [comment]
@Thr33D Did you get icons working?

**Comment by Thr33D** [comment]
It's weird...It seems like the icon disappears in the evening.  It shows up during the day and then when I come home at night it's off.

![screen shot 2018-09-27 at 9 57 40 pm](https://user-images.githubusercontent.com/43507964/46183767-76e3da00-c2a0-11e8-8afb-79f4d8be4f1c.png)

**Comment by cowboysdude** [comment]
Do a git pull to make sure you have all the icons.    They are all there :)

**Comment by Thr33D** [comment]
I will try that...but here is a screenshot from the morning...
<img width="317" alt="screen shot 2018-09-28 at 11 58 17 am" src="https://user-images.githubusercontent.com/43507964/46219658-de883c80-c315-11e8-892a-d027d3db0edf.png">

**Comment by Thr33D** [comment]
I then deleted the entire MMM-NOAA3 directory and reinstalled the module.  It still did not put the icon in the weather.

It's really weird as I have 2 other mirrors working without any problem.

**Comment by Thr33D** [comment]
Working in the morning again:
![screen shot 2018-09-29 at 8 36 55 am](https://user-images.githubusercontent.com/43507964/46245844-e651ea80-c3c2-11e8-82f9-7f27908f343f.png)

**Comment by Thr33D** [comment]
@cowboysdude So I am doing a little trouble shooting...at 7:50 PM my time (EST) the image disappeared.  It was there, (CLOUDS) and then just disappeared.  The text is still CLOUDS.  I don't have any other module that starts or interferes with that section of the screen.

**Comment by cowboysdude** [comment]
Very awesome!!!!

**Comment by Thr33D** [comment]
Yup...it seems to be based on the time...this is the module as of 11:55 AM EST:
![screen shot 2018-09-30 at 11 54 39 am](https://user-images.githubusercontent.com/43507964/46259456-a6186800-c4a7-11e8-8178-3dc40c2d2efb.png)

**Comment by cowboysdude** [comment]
Awesome!
