### ISSUE TITLE
Error: Cannot find module 'psl'

### ISSUE THREAD

**Issue by revere521** [cowboysdude/MMM-NOAA3#12]
Hello, i have been attempting to run this module and i keep receiving errors on load: 

I've reinstalled and rerun npm install to no avail. I believe that i have the config correct, can you verify (m api keys swapped out with 'xxx' and my location with '###' otherwise it is character for character including all quotations. 

`App threw an error during load
Error: Cannot find module 'psl'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/tough-cookie/lib/pubsuffix-psl.js:32:11)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/tough-cookie/lib/pubsuffix-psl.js:40:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'psl'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/tough-cookie/lib/pubsuffix-psl.js:32:11)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/tough-cookie/lib/pubsuffix-psl.js:40:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
`

`{
                        module: 'MMM-NOAA3',
                        position: 'top_right',
                                 config: {
                                        provider: "xxx", // From list above
                                        apiKey: 'xxx', // From one of the providers listed above
                                        css: "NOAA4", // THIS MUST CONTAIN A CSS STYLE NAME
                                        userlat: '###', //MUST HAVE BOTH
                                        userlon: '###'  //MUST HAVE BOTH
                                }
                },`

**Comment by cowboysdude** [comment]
Did you run npm install in the Noaa3 directory.

**Comment by revere521** [comment]
I did, and i've deleted the node_modules and re-run it as well. 

it looks like i have node v9.11.2 installed, is there a specific version this is intended for?

**Comment by revere521** [comment]
sorry and npm 6.1.0, im updating it to 6.4.1 - i will report if that solves the issue

**Comment by cowboysdude** [comment]
Not that I know of.   Not sure eat you have going on there

**Comment by revere521** [comment]
i updated everything, including mm to 2.5 - and now the framework loads for the module, but without the data (NANs and undefined) 

here is the mm-error-log
0|mm       |   errno: -2,
0|mm       |   code: 'ENOENT',
0|mm       |   syscall: 'open',
0|mm       |   path: 'modules/MMM-NOAA3/latlon.json' }
0|mm       | SyntaxError: Unexpected token G in JSON at position 0
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-NOAA3/node_helper.js:66:33)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Request.emit (events.js:214:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1161:10)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:313:30)

**Comment by cowboysdude** [comment]
Then something is wrong with your config it sounds like

**Comment by revere521** [comment]
what should the content of modules/MMM-NOAA3/latlon.json be?  can you give me an example of the formatting  of the code in that file?

**Comment by cowboysdude** [comment]
module: 'MMM-NOAA3',
position: 'top_left',
   config: {
       provider: "must be in quotes", // From list above
       apiKey: "YOUR API KEY",        // From one of the providers listed above
       airKey: "YOUR API KEY",    
       css: "NOAA3",                   
      userlat: "42.596790",
     userlon: "-82.878340"
}
    },

**Comment by cowboysdude** [comment]
Are you getting errors in the console log?

**Comment by revere521** [comment]
Yes I am sir: 

If i manually populate the info you provide in the **latlon.json** - the error in the log is:

0|mm       | Whoops! There was an uncaught exception...
0|mm       | SyntaxError: Unexpected token m in JSON at position 3
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Object.addModuleConfiguration (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ds.js:37:28)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-NOAA3/node_helper.js:40:27)
0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Socket.emit (events.js:214:7)
0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm       |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:180:9)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Create new news fetcher for url: http://wnep.com/feed/ - Interval: 300000
0|mm       | Whoops! There was an uncaught exception...
0|mm       | SyntaxError: Unexpected token G in JSON at position 0
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-NOAA3/node_helper.js:66:33)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Request.emit (events.js:214:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1161:10)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:313:30)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues


If i remove latlon.json and assume it will be created when running the module - i get the following error (also reported in the other bug report)

 Whoops! There was an uncaught exception...
0|mm       | { Error: ENOENT: no such file or directory, open 'modules/MMM-NOAA3/latlon.json'
0|mm       |     at Object.fs.openSync (fs.js:646:18)
0|mm       |     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
0|mm       |     at Object.fs.readFileSync (fs.js:551:33)
0|mm       |     at Object.fs.readFileSync (ELECTRON_ASAR.js:510:29)
0|mm       |     at Object.addModuleConfiguration (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/ds.js:36:20)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-NOAA3/node_helper.js:40:27)
0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Socket.emit (events.js:214:7)
0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm       |   errno: -2,
0|mm       |   code: 'ENOENT',
0|mm       |   syscall: 'open',
0|mm       |   path: 'modules/MMM-NOAA3/latlon.json' }
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Create new news fetcher for url: http://wnep.com/feed/ - Interval: 300000
0|mm       | Whoops! There was an uncaught exception...
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | SyntaxError: Unexpected token G in JSON at position 0
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-NOAA3/node_helper.js:66:33)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Request.emit (events.js:214:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1161:10)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:313:30)


The Placeholders for the module load, but this no actual data populated from the API

**Comment by cowboysdude** [comment]
Well that's easy it NO longer uses that file.....here's an example config from the instructions:

{
     module: 'MMM-NOAA3',
 position: 'top_left',
     config: {
 	    provider: "Yahoo",   
 	    airKey: "YOUR API KEY", 
         css: "NOAA3",                 // THIS MUST CONTAIN A CSS STYLE NAME 
 	userlat: "xxxx", //MUST HAVE BOTH
         userlon: "xxxx"  //MUST HAVE BOTH
 }
 },
You MUST input your lat and lon into the config file in your main config.js file for MagicMirror see above.

**Comment by revere521** [comment]
I absolutely, positively have that config in in config.js

Here it is again (as in the first post) - that is the module config from my /config/config.js

{
                        module: 'MMM-NOAA3',
                        position: 'top_right',
                                 config: {
                                        provider: "darksky", // From list above
                                        apiKey: "my actual api key is here, i just removed it from the post", // From one of the providers listed above
                                        airKey: "my actual api key is here, i just removed it from the post",
                                        css: "NOAA4", // THIS MUST CONTAIN A CSS STYLE NAME
                                        userlat: "41.540470", //MUST HAVE BOTH
                                        userlon: "-75.945630"  //MUST HAVE BOTH
                                }
                },

**Comment by cowboysdude** [comment]
Install TeamViewer so I can log on and see the issue.  :)  I'm available right now as I'm waiting on someone else to show up at my house.......

**Comment by revere521** [comment]
is there a way to privately send you my teamviewer id?

**Comment by cowboysdude** [comment]
Yes go onto the MagicMirror forum and send me a PM :)

**Comment by cowboysdude** [comment]
ALL fixed Thanks to you!! Thank you for finding a serious flaw for MANY that I didn't even know what there!!

**Comment by kumailraza404** [comment]
can you share the steps to solve this issue?
