### ISSUE TITLE
Openweather 4 day forecast

### ISSUE THREAD

**Issue by joberbr** [cowboysdude/MMM-NOAA3#16]
when using the openweather api, the 4 day forecast is not appearing.

![image](https://user-images.githubusercontent.com/40904517/47583505-8b9da700-d90c-11e8-9168-b09b00445de4.png)

![image](https://user-images.githubusercontent.com/40904517/47583582-c43d8080-d90c-11e8-86b8-ec9df89f44be.png)

**Comment by cowboysdude** [comment]
For some strange reason and I can't quite figure out why it will show if you reload the mirror....

Basically when you start the mirror hit the 'Alt' key.....go to the top and "View" then hit "Reload".....then it shows up.  Not sure why.  But that's how it works.

My biggest suggestion has always been the same which is DarkSky if far more accurate and works better.

**Comment by joberbr** [comment]
Thanks so much!! I appreciate your help. It is a great module.

**Comment by cowboysdude** [comment]
That issue I believe has been solved :)  Do a git pull to update.
