### ISSUE TITLE
Not seeing 4 day forecast

### ISSUE THREAD

**Issue by merceg100** [cowboysdude/MMM-NOAA3#2]
I have widget on my magic mirror screen but beneath 4 day forecast nothing shows:

![untitled-3](https://user-images.githubusercontent.com/41470213/43254963-d8c39e86-90c8-11e8-83fe-805e8d0e85f5.png)
![untitled-4](https://user-images.githubusercontent.com/41470213/43254965-d8e326d4-90c8-11e8-9bfe-9095fe063492.png)

Did I forgot to add something?
If so could You pinpoint me to possible solution. Although I made everything from scratch using tutorials all over internet and this forum I am still newbie in this project.
TNX!

**Comment by cowboysdude** [comment]
That happens with openweather from time to time.   Just refresh it may take
a couple times.
