### ISSUE TITLE
4 day Forecast Issue

### ISSUE THREAD

**Issue by swvalenti194** [cowboysdude/MMM-NOAA3#21]
First off awesome build.  All works minus the 4 day forecast.  I see the bottom bar and it says 4 day forecast but the forecast doesn't display.    I used openweather, airvisual and lat long as suggested.  Even when I hit 4day on touch screen forecast no go etc.   Any ideas?
![w error](https://user-images.githubusercontent.com/43345060/48517198-8fe62180-e833-11e8-8aab-59c2c5e95279.PNG)

**Comment by cowboysdude** [comment]
It's a common glitch    reload fixes it

**Comment by swvalenti194** [comment]
I restarted mm and also refreshed chrome page several times to no avail....any other ideas?

**Comment by cowboysdude** [comment]
What provider are you using

**Comment by swvalenti194** [comment]
openweather

**Comment by swvalenti194** [comment]
{   module: 'MMM-NOAA3',
position: 'top_right',
   config: {
       provider: "openweather", // From list above
       apiKey: "5ecacf9f7e4b567f8d4f33890fa5ee64",        // From one of the providers listed above
       airKey: "gh8hixgecHLH7cuFK",    
       css: "NOAA4",                   // THIS MUST CONTAIN A CSS STYLE NAME 
   userlat: "40.19650", //MUST HAVE BOTH
       userlon: "-74.16847"  //MUST HAVE BOTH
}
    },

**Comment by swvalenti194** [comment]
Ok so I did
![mmm noaa3 update](https://user-images.githubusercontent.com/43345060/48649036-4de9e680-e9bf-11e8-911b-1d6fb2cafba2.PNG)
 darksky...but now I get this...

**Comment by swvalenti194** [comment]
Now I get this from going to darksky
![mmm noaa3 update](https://user-images.githubusercontent.com/43345060/48649227-ee400b00-e9bf-11e8-8991-1e252cfc6b6f.PNG)

**Comment by swvalenti194** [comment]
update available......
