### ISSUE TITLE
It's got to be something I'm over looking

### ISSUE THREAD

**Issue by jonathancole85** [cowboysdude/MMM-NOAA3#22]
No matter what I do it will not populate the fields properly.

**Comment by cowboysdude** [comment]
What provider are you using?

**Comment by jonathancole85** [comment]
Weatherunlocked

**Comment by cowboysdude** [comment]
Please post a picture of what you're getting.

**Comment by jonathancole85** [comment]
It's finally started showing rise, set, daylight and AQI. Only after I ran an upgrade command.

**Comment by jonathancole85** [comment]
Undefined in all fields except temp renders NaN°

**Comment by cowboysdude** [comment]
Okay so it's working now?

**Comment by jonathancole85** [comment]
No

**Comment by jonathancole85** [comment]
Just rise daylight set and AQI are giving and data. And it does appear to be accurate. Where before rise and set where all that gave anything but it was the actual time and it changed with each minute

**Comment by cowboysdude** [comment]
Run the mirror in npm start dev mode and see if you're getting any errors.

**Comment by jonathancole85** [comment]
I do appreciate your help with this. Thank you

**Comment by cowboysdude** [comment]
You're welcome but it's really hard not being able to see it....  Do you
have teamviewer installed?

**Comment by jonathancole85** [comment]
Yes I'm just learning this stuff so you may have to break it down elementary school for me.

**Comment by cowboysdude** [comment]
Go here and download TeamViewer and install it.
It allows people to log into your computer and see what's going on.
People can only log in if you give them the new password each time
TeamViewer runs so it's not a security risk.

https://www.teamviewer.com/en-us/download/linux/
[Windows version is there too if you need that one]

You install it..... run it and it gives you a log in and password that you
give to the other person [me] and I can log in and run the mirror so I can
see what it's doing.

**Comment by jonathancole85** [comment]
I assume you need this id

**Comment by jonathancole85** [comment]
1118070244

**Comment by cowboysdude** [comment]
Need your login and the password :)

**Comment by jonathancole85** [comment]
jonathancole85@yahoo.com
Dogface1!

**Comment by jonathancole85** [comment]
And the actual pi password is dogface1

**Comment by cowboysdude** [comment]
If you installed TeamViewer then it gives you a login and password.....

That's what I need :)

**Comment by jonathancole85** [comment]
It's having me log in get it on my trusted devices list

**Comment by jonathancole85** [comment]
I promise I'm going as quickly as I know how

**Comment by cowboysdude** [comment]
Oh you're doing fine........

Where do you live?

**Comment by jonathancole85** [comment]
Manhattan Ks

**Comment by jonathancole85** [comment]
Is it my display name you're in need of?

**Comment by jonathancole85** [comment]
It's keeps saying my account needs to be activated. But I've done that

**Comment by jonathancole85** [comment]
It's not letting me do much but what I have done. The pi is ColePi2 says my id is 192.168.1.1; 169.254.245.247

**Comment by jonathancole85** [comment]
The password I have to login to my account is Dogface1! The password I have within the pi is dogface1

**Comment by jonathancole85** [comment]
I hope this is the right information

**Comment by cowboysdude** [comment]
Well that took longer then I wanted it to LOL
If you're around we can try it again.

**Comment by cowboysdude** [comment]
Tried to get a hold of you but you're not answering......if the issue persists then you can reopen this :)

**Comment by jonathancole85** [comment]
I do apologise, I had a family emergency I needed to focus on. I have tried a few more things to no avail. Including starting all over with a fresh sd card. If you have the time I would greatly appreciate your help. I'm installing TeamViewer right now
