### ISSUE TITLE
AccuWeather Zip Code 

### ISSUE THREAD

**Issue by rob2791** [cowboysdude/MMM-NOAA3#24]
It seems that when using Accuweather, the zip code needs to be the 6 digit code from accuweather.com's website found after typing in the zip code into their search bar. 
From Zip Code "13502" returns "329671"-which is what I put in my config file in order to get it to display local weather.
 `zip: '329671', //MUST have valid zip Code`

https://www.accuweather.com/en/us/utica-ny/13502/weather-forecast/329671

**Comment by cowboysdude** [comment]
Thank you for that info!! I'll change the README :)
