### ISSUE TITLE
updates when i restart MM and will update once after, but will not update anymore after 

### ISSUE THREAD

**Issue by mustang5676** [cowboysdude/MMM-NOAA3#27]
i recently installed this module, every thing seems to be working however once i start the mirror it will update the weather then it will update once after that at the selected interval rate. but will not updated anymore unless i force reload the mirror.   i have reinstalled the module, and mirror and have the same issue on 2 separate ras pi's one with a config straight from install, and a custom. i'm using darksky and have checked the allowed api calls which is 1,000 per day i believe i also have checked my activity in darksky and its registering the calls.  was there an update or a change recently that might have caused this? or am i missing something?  thanks for any help and this module!! 

here are my configs

{
                        disabled: false,
                        module: 'MMM-NOAA3',
                        position: 'top_right',
                        config: {
                                provider: "darksky",
                                apiKey: "##########",        
                                airKey: " ###########",
                                css: "NOAA2",
                                updateInterval: 15 * 60 * 1000,               
                                userlat: "####", 
                                userlon: "-####"  
                         }
                },

**Comment by cowboysdude** [comment]
Do a git pull and try the update ;)

**Comment by mustang5676** [comment]
thanks! i will give thata try and see what happens

**Comment by cowboysdude** [comment]
Please do!

**Comment by mustang5676** [comment]
any other ideas? get pull did not work.

**Comment by cowboysdude** [comment]
I really don't.  I can't reproduce your issue.  I have talked to a couple
people and no one else is having this problem.  So not really sure.

**Comment by mustang5676** [comment]
hmm thats weird as i have installed the repository straight from github on 2 different machines and have not changed any of the json files other than api key and lat and long. and have the issue on BOTH  of them. i would have thought the creator of this module would have a little bit more insight other than just run git pull. but none the less thanks for the help
