### ISSUE TITLE
Not Getting any data

### ISSUE THREAD

**Issue by txajay** [cowboysdude/MMM-NOAA3#28]
First I want to thank you for designing this module.  Looks great.  As an FYI... I am new here, so bare with me if I get too details or use the incorrect terminology.  In the process of building my MagicMirror, I I was disappointed by the default weather option, openweather.  The temps and time are completely off atleast by 10 degrees.  Anyhow, found your module using Accuweather and figured I'd give that a shot.  

I create the Airkey but could not find from the accuweather how to get their key.  Then I looked at the API example for accuweather and noticed the API for accuweather is not needed in there.  Here is my module code: 

		{
     			module: "MMM-NOAA3",
 			position: "top_right",
     			config: {
 				provider: "accuweather",   
 				airKey: "XXXXXXXXXXXXXXXXXXXX", 
         			css: "NOAA4",                 // THIS MUST CONTAIN A CSS STYLE NAME 
 				userlat: "29.794861", //MUST HAVE BOTH
         			userlon: "-95.816528",  //MUST HAVE BOTH
 				zip: "77494" //MUST have valid zip Code
 			}

When I run magicmirror doing this, I get no values and it says NAN.  I've tried to attach the file for reference.  

![20190101_013757](https://user-images.githubusercontent.com/46292765/50571096-3fd10900-0d66-11e9-96a4-74abc587db51.jpg)

I was hoping if someone could help me out with this.  It be much appreciated.  Thanks.

**Comment by cowboysdude** [comment]
You don't have an api Key for the weather...  therefore you won't get any
data

**Comment by txajay** [comment]
John,

I tried the openweathermap key and it's ridiculously off.  Does AccuWeather
provide free api keys?

In your code snippet for the config file, I did not see a place for the api
key to go.  You did show where the air key goes in the example you posted.

Sorry for these annoying questions.  New to all this so figuring it out as
I go along.

What weather api key do you use?

Thanks,
Ajay

**Comment by cowboysdude** [comment]
Yes.  Everyone I use is free ;)
