### ISSUE TITLE
Mismatching reference into moon array ("Waxing" vs "Waxing Crescent")

### ISSUE THREAD

**Issue by alexlobrano** [cowboysdude/MMM-NOAA3#32]
Not sure if this is provider dependent or not (I'm using Accuweather), but I just noticed I was getting a missing moon icon under the "Night" part of the module tonight. I did a little digging and noticed this.moon was being set to "Waxing Crescent" but there is no matching element for "Waxing Crescent", only for "Waxing". I changed "Waxing" to "Waxing Crescent" in this.config.moon and that solved the problem. Not sure if you want a PR for this or you can just push an update yourself or if it's a specific issue with Accuweather that requires no change, but thought I'd mention it 👍

**Comment by swvalenti194** [comment]
![img_20190110_185439](https://user-images.githubusercontent.com/43345060/51004781-35530400-150a-11e9-9d18-1470c2a7fdba.jpg)

Interestingly, after the most recent update I don't have a moon display at all?

**Comment by alexlobrano** [comment]
When was the last time you updated? The moon line was changed in November from "Waxing Crescent" to just "Waxing", which is what I changed back, so that could be your issue too

**Comment by cowboysdude** [comment]
Fixed the moon issue :)  Some providers report it as just "Waxing" and some "Waxing Crescent"  so now that's fixed for all providers!  Great catch and Thank you!!!
