### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by technoid5918** [cowboysdude/MMM-NOAA3#37]
Missing image for Breezy, other images work, just not this one.
![ScreenShot001](https://user-images.githubusercontent.com/3422648/56100619-138e6200-5ee9-11e9-8790-1fe49658212e.jpg)

**Comment by cowboysdude** [comment]
Fixed :)  Thank you!

**Comment by technoid5918** [comment]
Thanks

I'm very happy with the app, and would like to thank you for sharing it.
