### ISSUE TITLE
Just getting a black screen

### ISSUE THREAD

**Issue by rvsphinx** [cowboysdude/MMM-NOAA3#4]
I have configured as stated in the readme but when I run it shows blank screen on the top right.  I see your config doesn't have a position stated.  I also tried adding postion: 'top-right', and it kills other modules I have. Not sure if its because of the CSS but still not loading any graphics or data.  please help I love the way the css look.  Im am using darksky api key and my airvisual api as well.

**Comment by cowboysdude** [comment]
Do you use Teamviewer by any chance?  I could take a look at your config.
