### ISSUE TITLE
Weatherbit provider missing

### ISSUE THREAD

**Issue by Tom-Hirschberger** [cowboysdude/MMM-NOAA3#4]
Hi,

i use the module for some years now and copied the from an old mirror installation last time because of the missing repository.
Today i updated my mirror and wanted to change back to the offical repository of NOAA3 and did a fresh clone.
At the first start a got an error and saw that the wb.js provider file is missing.
Did you drop weatherbit support? It is still functional with the old file with only one error in the log that "pollution" could not be read.

**Comment by cowboysdude** [comment]
They are all there now! :)  Didn't realize they didn't upload!  Thank you!
