### ISSUE TITLE
All seems ok but I obtain undefined.

### ISSUE THREAD

**Issue by technofab** [cowboysdude/MMM-NOAA3#43]
Hi All, I'm stuck in this error:
![NOAA](https://user-images.githubusercontent.com/14272723/71579069-1e326b00-2afb-11ea-910e-ccba4a1df6eb.jpg)

I'm from Florence in Italy, and I'm assuming there is coverage from this service.
That is my config, and pay attention I've subscribed the free version for both api's.

{
    module: 'MMM-NOAA3',
    position: "top_center",
    config: {
        provider: "weatherbit",
        apiKey: "",  // weatherbit api key
        airKey: "",  // airvisual api key
        css: "NOAA3",
        userlat: "43.777699",
        userlon: "11.290828"
}

What am I missing?

**Comment by cowboysdude** [comment]
Did you enter a weatherbit api key and airvisual api key?  If not it will never work.

**Comment by technofab** [comment]
Yes, sure I masked them for privacy but I can post them if necessary.. I wait many minutes, also days until now, but still in NaN.. I set css to NOOA3; what you stand for latest test?!

**Comment by romka-elvis** [comment]
Hi! I have exactly the same issue like @technofab . My openweather API works fine with the standard module "weatherforecast". I also tried to enter coordinates of bigger cities nearby but it didn't help.  Also I tried all possible CSS designs. 
![photo_2020-01-03_00-23-16](https://user-images.githubusercontent.com/59457122/71699339-49e57780-2dbf-11ea-91f6-e852b10388ac.jpg)
Here how my config.js looks like:

{
			module: 'MMM-NOAA3',
			position: "top_right",
    			config: {
	    			provider: "openweather",   
	    			airKey: "xxxxxxxx",
 				airKey: "xxxxxxxx",
        			css: "NOOA3",   // THIS MUST CONTAIN A CSS STYLE NAME
	    			updateInterval: 30 * 60 * 1000, // every 30 minutes 
	   			userlat: "48.740879", //MUST HAVE BOTH
           			userlon: "9.308240"  //MUST HAVE BOTH 
				}
		}

**Comment by technofab** [comment]
Just my 2 cents @romka-elvis : why double "AIRKEY" ? One must be "APIKEY".

**Comment by romka-elvis** [comment]
@technofab thanks, didn‘t notice that. I‘ll check the config again, maybe it was the error reason.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romka-elvis** [comment]
![photo_2020-01-03_16-24-27](https://user-images.githubusercontent.com/59457122/71731753-d0dd3300-2e45-11ea-85a5-add5ae08d517.jpg)
Actual weather seems to work no, but the forecast is missing.

**Comment by technofab** [comment]
I also made a little step up
![NOAA](https://user-images.githubusercontent.com/14272723/71735335-73011900-2e4e-11ea-940b-4f1a4a488ec4.jpg)
In the red square seems to miss an image, and are some invalid date on the yellow square...

**Comment by MarkNygaard** [comment]
I have the same undefined image. So don't think it is just for you. 
However, would be nice to get it solved.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/47065655/71745934-ea917100-2e6b-11ea-943f-2dad2b8ba1a9.png">

**Comment by technofab** [comment]
Partially solved.. the invalid date, am/pm notation and the missing image, come from the 2 service or they are a bug/malfunction?!

**Comment by romka-elvis** [comment]
I changed the weather provider to [darksky](https://darksky.net/) and it worked for me.

<img src="https://user-images.githubusercontent.com/59457122/71766218-ced6ab00-2efd-11ea-87df-524ca5a5ee6e.jpg" width="300">

**Comment by technofab** [comment]
Changing provider something change, but not the time notation. Any idea?
![NOAA](https://user-images.githubusercontent.com/14272723/71879105-92899180-312d-11ea-8a1c-9150ada7e312.jpg)

**Comment by cowboysdude** [comment]
> 
> 
> I have the same undefined image. So don't think it is just for you.
> However, would be nice to get it solved.
> 
> <img alt="image" width="182" src="https://user-images.githubusercontent.com/47065655/71745934-ea917100-2e6b-11ea-943f-2dad2b8ba1a9.png">

I think it may be that the translate files may not have the 'moon phases' in there.....  I'll have to check!

**Comment by cowboysdude** [comment]
> 
> 
> Changing provider something change, but not the time notation. Any idea?
> ![NOAA](https://user-images.githubusercontent.com/14272723/71879105-92899180-312d-11ea-8a1c-9150ada7e312.jpg)

Are you referring to the number of hours in the say?  The problem is there doesn't seem to be enough room for the translation..... is there a word that would work in place of what's in the translation file?  Thanks!

**Comment by cowboysdude** [comment]
> 
> 
> I changed the weather provider to [darksky](https://darksky.net/) and it worked for me.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/59457122/71766218-ced6ab00-2efd-11ea-87df-524ca5a5ee6e.jpg">

Yes DarkSky seems to be the one that works best...... it can be due to time it takes to pole the api versus the others..... it would also be depending on country....

**Comment by cowboysdude** [comment]
> 
> 
> Hi All, I'm stuck in this error:
> ![NOAA](https://user-images.githubusercontent.com/14272723/71579069-1e326b00-2afb-11ea-910e-ccba4a1df6eb.jpg)
> 
> I'm from Florence in Italy, and I'm assuming there is coverage from this service.
> That is my config, and pay attention I've subscribed the free version for both api's.
> 
> {
> module: 'MMM-NOAA3',
> position: "top_center",
> config: {
> provider: "weatherbit",
> apiKey: "", // weatherbit api key
> airKey: "", // airvisual api key
> css: "NOAA3",
> userlat: "43.777699",
> userlon: "11.290828"
> }
> 
> What am I missing?

Nothing........ go to DarkSky it works best for places outside the US for some reason

**Comment by cowboysdude** [comment]
> 
> 
> I changed the weather provider to [darksky](https://darksky.net/) and it worked for me.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/59457122/71766218-ced6ab00-2efd-11ea-87df-524ca5a5ee6e.jpg">

Hate to ask but is there better words I can use in the translation file to shorten the AQI?  I may have to switch back to numbers...... long translations throws all the alignment off :(

**Comment by romka-elvis** [comment]
>>  ...

@cowboysdude I will take a look at German translation. There is some potential for improvement:)

**Comment by technofab** [comment]
@cowboysdude sorry for my poor english, you mean that you need something for italian translation? I'm welcome to help you!

**Comment by romka-elvis** [comment]
> > I changed the weather provider to [darksky](https://darksky.net/) and it worked for me.
> > <img alt="" width="300" src="https://user-images.githubusercontent.com/59457122/71766218-ced6ab00-2efd-11ea-87df-524ca5a5ee6e.jpg">
> 
> Hate to ask but is there better words I can use in the translation file to shorten the AQI? I may have to switch back to numbers...... long translations throws all the alignment off :(

@cowboysdude  this is how I configured my German translation file:

`{
"Rise":"AUF",
"Set":"UNTER", 
"4 Day Forecast":"4-Tage-Prognose",
"Monday": "Montag",
"Tuesday": "Dienstag",
"Wednesday": "Mittwoch",
"Thursday": "Donnerstag",
"Friday": "Freitag",
"Saturday": "Samstag",
"Sunday": "Sonntag",
"Hours of Light":"hell",
"Last Updated": "Aktualisiert",
"Today":"Heute",
"Night":"Nacht",
"Mon":"Mo",
"Tue":"Di",
"Wed":"Mi",
"Thu":"Do",
"Fri":"Fr",
"Sat":"Sa",
"Sun":"So",
"No Wind": "still",
"Humidity": "Feuchte",
"Visibility":"Sicht",
"Pressure":"Druck",
"Excellent":"Sehr gut",
"Good":"Gut",
"Lightly Polluted":"befriedigend",
"Moderately Polluted":"schlecht",
"Heavily Polluted":"sehr schlecht",
"Forecast":"Prognose"
}`

**Comment by NelsonSanto** [comment]
Hi cowboydude im from portugal i already translate to send to you i did some teste but i have some error np 1 package is looking for fundinh
mmm-noaa3 @3.0.0 public ip @4.0.0 sponsors /sindresorhus

translate file to portuguese

TRanslate to portuguese


“Previsao do tempo”: 
"Currently: ": "Temperatura: ",
"Current Temp: ": "Temperatura Actual: ",
"UV Index ": "Índice Uv :",
"Wind: ": "Vento: ",
"From: ": "De: ",
"Barometer: ": "Barômetro ",
“~~~ Previsão ~
": "~ Prognóstico ~~~
”,
“Monday”: “Segunda-feira”,
“Tuesday”: “Terça-feira”,
“Wednesday”: “Quarta-feira”,
“Thursday”: “Quinta-feira”,
“Friday”: “Sexta-feira”,
“Saturday”: “Sábado”,
“Sunday”: “Domingo”,
“Overcast”: “Encoberto”,
“Cloudy”: “Nublado”,
“Rain”: “Chuva”,
“Clear”: “Limpo”,
“Partly Cloudy”: “Parcialmente Encoberto”,
"High: ": "Elevado: ",
"Low: ": "Baixo: ",
"Humidity: ": "Humidade: ",
“Safe”: “Seguro”,
“Moderate”: “Moderado”,
“Snow showers”: “Aguaceiros Neve”,
“Very High”: “Muito Alto”,
“Extreme”: “Extremo”,
“Sunset”: “Pôr do sol”,
“Sunrise”: “Nascer do sol”,
“hours”: “houras”,
“minutes”: “minutos”,
“Amount of Daylight”: “Duração Luz do Dia”

**Comment by cowboysdude** [comment]
I will update Thank you for the translation.   :)
