### ISSUE TITLE
humidity display problem

### ISSUE THREAD

**Issue by jackasscouille** [cowboysdude/MMM-NOAA3#46]
hi
there is a slight bug
when there is 100% air humidity the display shows 1%, below no problems
module: 'MMM-NOAA3',
			position: 'top_left',
				config: {
				provider: "darksky", // From list above
				apiKey: "xxxxxxxx",        // From one of the providers listed above
				airKey: "xxxxxxxx",    
				css: "NOAA3",                   // THIS MUST CONTAIN A CSS STYLE NAME 
				userlat: "xxxxx", //MUST HAVE BOTH
				userlon: "xxxx"  //MUST HAVE BOTH

**Comment by cowboysdude** [comment]
That is going to require a provider file rewrite.  I will get to it ASAP but right now I just don't have time.....scary in a world where everyone has nothing but time right now ;)
