### ISSUE TITLE
NOAA API

### ISSUE THREAD

**Issue by mrlowndes** [cowboysdude/MMM-NOAA3#47]
Sorry to open an issue - didn't know how else to get in touch with the developer. I'm looking for a way to implement local weather station forecasts into my magic mirror and use local NOAA weather stations like this example: https://forecast.weather.gov/MapClick.php?lat=37.6306&lon=-120.9576

Is there any way to have your module us NOAA as the provider? I think you can get an API key through this portal: https://www.ncdc.noaa.gov/cdo-web/webservices/v2

Thanks

**Comment by cowboysdude** [comment]
Not built to do that..
