### ISSUE TITLE
provider openmapweather

### ISSUE THREAD

**Issue by lacalos** [cowboysdude/MMM-NOAA3#5]
hi. thank you for this module.. i love this.
but sorry in folder "provider" miss ow.js "openmapweather".. please

**Comment by cowboysdude** [comment]
Sorry didn't realize they weren't there, they are now :)  Thank you!

**Comment by lacalos** [comment]
Sorry master. I have a problem with module.. I use providers ow.js
openmapweather ... But I don't see 4 days forecast. How to resolve this?
Thank you

Il gio 21 apr 2022, 14:06 John Wade ***@***.***> ha scritto:
