### ISSUE TITLE
no weather data

### ISSUE THREAD

**Issue by brusslesprouts** [cowboysdude/MMM-NOAA3#50]
Installed and shows up followed just as described used weatherunlocked for my info.
 put it all there with the keys and everything and get no weather at all says not detected but the module shows up.

here is my config
		   {
     module: 'MMM-NOAA3',
 position: 'top_right',
     config: {
 	    provider: "weatherunlocked",       
 	    apiKey: "0d1aa9b6e7fac3149107e4aba2c08a6b",  
 	    appID: "008f93f4",  
 	    airKey: "eecafb55-c45e-41f2-85d3-d792f9740849", 
         css: "NOAA4",
           updateInterval: "15",                
 	userlat: "37.440319", //MUST HAVE BOTH
         userlon: "121.912231"  //MUST HAVE BOTH
  }
		},

**Comment by cowboysdude** [comment]
There is a problem with that service.  Sometimes they do not send the required data back and I can't fix that.   I would suggest you try a different provider.  :)
