### ISSUE TITLE
Portuguese translation_if you want

### ISSUE THREAD

**Issue by damag3** [cowboysdude/MMM-NOAA3#51]
Hi thank you for the great module. I did the translation to Portuguese in case you wanted

`{
"Rise":"Nascer do Sol",
"Set":"Pôr do Sol", 
"4 Day Forecast":"Previsão para 4 dias",
"Monday": "Segunda",
"Tuesday": "Terça",
"Wednesday": "Quarta",
"Thursday": "Quinta",
"Friday": "Sexta",
"Saturday": "Sabado",
"Sunday": "Domingo",
"Hours of Light":"Horas de luz",
"Last Updated": "Última atualização",
"Today":"Hoje",
"Night":"Noite",
"Mon":"Seg",
"Tue":"Ter",
"Wed":"Qua",
"Thu":"Qui",
"Fri":"Sex",
"Sat":"Sab",
"Sun":"Dom",
"No Wind": "Sem vento",
"Humidity": "Humidade",
"Visibility":"Visibilidade",
"Pressure":"Pressão",
"Excellent":"Excelente",
"Good":"Boa",
"Lightly Polluted":"Pouca Poluição",
"Moderately Polluted":"Média Poluição",
"Heavily Polluted":"Altamente Poluido",
"Forecast":"Previsão"
}`

**Comment by cowboysdude** [comment]
Sorry I haven't been on!! Yes I would love to have this!  Thank you for doing it!!!
