### ISSUE TITLE
Weather seems never correct any ideas?

### ISSUE THREAD

**Issue by dyard12** [cowboysdude/MMM-NOAA3#52]
Weather seems never correct any ideas? What I have wrong, I verified the location. Im using weather bit

**Comment by dyard12** [comment]
update I have updated my lattitude a longitude, its closer but still off by some degrees. I tried to use acuweather but then got no  weather. So I went back to weatherbit

**Comment by dyard12** [comment]
I changed the weather API to AccuWeather and it was correct but after a reboot seems 10 degrees off. Any suggestions on how to fix this?

**Comment by cowboysdude** [comment]
Not really.   It's how they are sending the data back.  I cannot control that which is too bad.  The weather API's now are horrid.
