### ISSUE TITLE
Wounderground possible?

### ISSUE THREAD

**Issue by c1olli** [cowboysdude/MMM-NOAA3#53]
Hello,
this is not a real issue, but I have a new Weatherstation and this sends the Data to WunderGround, but all MMM-modules aren't working anymore.
I have an API from Wounderground and can't get now the Data on my mirror. Do you have a solution for it?
I cannot code - sorry.

Merry Christmas
c1olli

**Comment by cowboysdude** [comment]
Only if you want to pay for the data but with that in mind it isn't written to use WunderGround.
