### ISSUE TITLE
Temp error when looking at centigrade. 

### ISSUE THREAD

**Issue by Grahamrich1** [cowboysdude/MMM-NOAA3#8]
I love the look of this module and set it up on my MagicMirror.  I trued to use the Weatherbit.io initially after a few issues, switched to Yahoo.  I'm using Long and Lat for Rochester in Kent, UK and when I look at TEMP in imperial is shows me the correct numbers (71 today). When I look at metric, instead of showing 22, I am seeing 54 degrees.  Is this a fault with the incoming data or does the conversion happen on the module?

**Comment by Grahamrich1** [comment]
timeFormat: 24,
	units: "metric",
	colored: "true", 

	modules: [  {
		     	module: 'MMM-NOAA3',
 			position: 'top_right',
     			config: {
 	    			provider: "Yahoo",   
 	    			airKey: "YOUR API KEY", 
         			css: "NOAA3",                 // THIS MUST CONTAIN A CSS STYLE NAME 
 				userlat: "51.39", //MUST HAVE BOTH
       				userlon: "0.51"  //MUST HAVE BOTH

**Comment by Grahamrich1** [comment]
An additional observation is that the temp for today at the top is wrong, but the forecast for the next 4 days appears correct.

**Comment by cowboysdude** [comment]
All fixed :)

**Comment by cowboysdude** [comment]
Nice catch I appreciate it!!  I have fixed the yahoo provider file and it
now shows the correct metric temps :)

Thank you!
John

**Comment by Grahamrich1** [comment]
Thanks John 


Kind Regards,
Graham Rich
Email:grahamrich1@me.com
Mobile: 07803 598587
