### ISSUE TITLE
everything showing undefined

### ISSUE THREAD

**Issue by AcidEdge** [cowboysdude/MMM-NOAA3#9]
just installed NOAA3. I'm using weatherbit for the api. location is mount clemens, MI. when i load the magic mirror the NOAA3 shows every part of the module as undefined. 

heres the code:

{
                        module: "MMM-NOAA3",
                        position: "top_right",
                        config: {
                                provider: "weatherbit",
                                apiKey: "***",
                                airKey: "***",
                                css: "NOAA2",
                                userLat: "42.596790",
                                userLon: "-82.878340",
                                }
                },

**Comment by cowboysdude** [comment]
Just used your entire config with my apikeys and it's showing me the weather......not sure what's going with yours.   Do a gitpull to make sure you have the newest and retry :)

**Comment by AcidEdge** [comment]
did a git pull, all is up to date. still showing all undefined. I tried using my openweather key (was using it originally for the default weather modules) and still not working. I just noticed this after exiting the magic mirror though:

Whoops! There was an uncaught exception...
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at Object.parseResponse (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/wb.js:86:28)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-NOAA3/providers/wb.js:80:28)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-NOAA3/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by Gavsdad** [comment]
I'm actually having the same exact issue. I also, just updated mine.

**Comment by AcidEdge** [comment]
so I just put used an api key for accuweather, and its working. it is limited, doesnt show all the data, but its at least showing something. Im looking into the other api keys, i think thats where im having the issue.

**Comment by Gavsdad** [comment]
So, maybe it's just the weatherbit api? That sucks. That one was actually giving me all the data. The module was actually working perfectly for me until I updated. I deleted and reinstalled without the update and it still wasn't working. Odd.

**Comment by AcidEdge** [comment]
its really odd. my openweather api key works great with the default weather modules, but im not crazy about them. i've tried the same openweather key with noaa3 and still get the undefined.

**Comment by Gavsdad** [comment]
Cowboysdude, which api are you using? Also, what does your config look like? I never had to add latitude and longitude and I never had a problem.

**Comment by AcidEdge** [comment]
did a git pull again. i have managed to get it to work mostly with the yahoo provider. air quality and uv index arent showing data, but i live metro detroit so its probably to bad for the system to read lol) and the sunrise/sunset doesn't work. is there a way to turn off the sunrise sunset? also - is there a way to change the size and make the module bigger?

**Comment by cowboysdude** [comment]
It's possible that there is no data for your location.   Remember not all
providers are equal.

**Comment by Gavsdad** [comment]
Alrighty........

**Comment by cowboysdude** [comment]
I would switch to darksky....it's honestly the most reliable.

**Comment by AcidEdge** [comment]
i did switch it to dark sky. I figured out that the providers scripts are not inserting the lat and long in the api request properly. I put it into the script manually (instead of the script using the json lat and long) and it works perfectly.

**Comment by anthony6608** [comment]
> i did switch it to dark sky. I figured out that the providers scripts are not inserting the lat and long in the api request properly. I put it into the script manually (instead of the script using the json lat and long) and it works perfectly.

Im having the same issue with Darksky, everything is undefined. Could you tell us specifically what files and where you edited? Trying to edit as well but I see 3 lines in the providers file with the lat/long call and not sure if those have to be edited or not.
